name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t DOCKER_USERNAME/my-python-app:latest .
          docker push DOCKER_USERNAME/my-python-app:latest

      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|image: DOCKER_USERNAME/my-python-app:.*|image: DOCKER_USERNAME/my-python-app:latest|" k8s/deployment.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add k8s/deployment.yaml
          git commit -m "Updated image to latest version"
          git push origin main
          
      - name: Trigger ArgoCD Sync
        run: |
          curl -X POST "http://<ARGOCD_SERVER>:<ARGOCD_PORT>/api/v1/applications/python-app/sync" \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'
