name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Convert Docker Username to Lowercase
        run: echo "DOCKER_USER=$(echo ${{ secrets.DOCKER_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_USER/my-python-app:latest .
          docker tag $DOCKER_USER/my-python-app:latest $DOCKER_USER/my-python-app:latest
          docker push $DOCKER_USER/my-python-app:latest

      - name: Debug - Show File Before and After
        run: |
          echo "Before update:"
          cat k8s/deployment.yaml
          sed -i "s|\(image: \).*my-python-app:.*|\1$DOCKER_USER/my-python-app:latest|" k8s/deployment.yaml
          echo "After update:"
          cat k8s/deployment.yaml

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes (If Needed)
        run: |
          git add k8s/deployment.yaml
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Updated image to latest version"
            git push origin main
          fi

      - name: Trigger ArgoCD Sync
        run: |
          curl -X POST "http://192.168.111.134:32165/api/v1/applications/python-app/sync" \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}'
